[tool.poetry]
name = "modelo-lamda"
version = "0.1.0"
description = ""
authors = ["Tecnologia"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
boto3 = "^1.34.135"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

