name: CI

on: [push]

jobs:
  pre-commit-and-test:
    name: Pre-commit and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Cache do Pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Instalar dependências
        run: |
          pip install pre-commit
          pip install coverage

      - name: Executar pre-commit
        run: pre-commit run -a --show-diff-on-failure

      - name: Executar testes com unittest
        run: python -m unittest discover tests

      - name: Executar testes de cobertura
        run: |
          coverage run -m unittest discover tests
          coverage report
          coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml