name: Python CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies and pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install pre-commit
          poetry install  # ou `pip install -r requirements.txt` se não estiver usando Poetry

      - name: Run pre-commit and tests
        run: |
          pre-commit run --all-files
          poetry run python -m unittest discover tests
          coverage run -m unittest discover tests

      - name: Check coverage and fail if less than 100%
        run: |
          coverage report -m --fail-under=100

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: .coverage

      - name: Final checks
        run: echo "All checks passed!"
